services:
  py313:
    image: srittau/uvicorn:3.13
    build:
      context: .
      args:
        - pyversion=3.13
  py312:
    image: srittau/uvicorn:3.12
    build:
      context: .
      args:
        - pyversion=3.12
  py311:
    image: srittau/uvicorn:3.11
    build:
      context: .
      args:
        - pyversion=3.11
  latest:
    image: srittau/uvicorn:latest
    build:
      context: .
      args:
        - pyversion=3.13
